"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getTextStringFromHtml = exports.formatDate = exports.wpLatestPublishedPostsByCategoryId = exports.wpPublishedPostsSlugsByCategoryId = exports.wpPostBySlug = exports.wpSiteInfo = exports.setConfig = void 0;
var functions_1 = require("./functions");
Object.defineProperty(exports, "setConfig", { enumerable: true, get: function () { return functions_1.setConfig; } });
Object.defineProperty(exports, "wpSiteInfo", { enumerable: true, get: function () { return functions_1.wpSiteInfo; } });
Object.defineProperty(exports, "wpPostBySlug", { enumerable: true, get: function () { return functions_1.wpPostBySlug; } });
Object.defineProperty(exports, "wpPublishedPostsSlugsByCategoryId", { enumerable: true, get: function () { return functions_1.wpPublishedPostsSlugsByCategoryId; } });
Object.defineProperty(exports, "wpLatestPublishedPostsByCategoryId", { enumerable: true, get: function () { return functions_1.wpLatestPublishedPostsByCategoryId; } });
var support_1 = require("./support");
Object.defineProperty(exports, "formatDate", { enumerable: true, get: function () { return support_1.formatDate; } });
Object.defineProperty(exports, "getTextStringFromHtml", { enumerable: true, get: function () { return support_1.getTextStringFromHtml; } });
